## Pandas
### Pandas  is open source python library for data manipulation and data analysis

In [145]:
import pandas as pd 

print(pd.__version__)

3.0.3

### DataFrame

In [146]:
df=pd.DataFrame([[None,22,33],[44,22,66],[77,88,99],[110,119,129]],index=[1,2,3,4],columns=["A","B","C"])
print(df)
print(df.head(1))
print(df.tail(1))

       A    B    C
1    NaN   22   33
2   44.0   22   66
3   77.0   88   99
4  110.0  119  129
    A   B   C
1 NaN  22  33
       A    B    C
4  110.0  119  129

In [147]:
print(df.columns)
print(df.index.to_list())
print(df.info())
print(df.describe())
print(df["B"].nunique())
print(df["B"].unique())
print(df.shape)

Index(['A', 'B', 'C'], dtype='str')
[1, 2, 3, 4]
<class 'pandas.DataFrame'>
Index: 4 entries, 1 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: float64(1), int64(2)
memory usage: 128.0 bytes
None
           A           B           C
count    3.0    4.000000    4.000000
mean    77.0   62.750000   81.750000
std     33.0   48.726276   41.451779
min     44.0   22.000000   33.000000
25%     60.5   22.000000   57.750000
50%     77.0   55.000000   82.500000
75%     93.5   95.750000  106.500000
max    110.0  119.000000  129.000000
3
[ 22  88 119]
(4, 3)

### Loading in Dataframes From files

In [148]:
coffee=pd.read_csv("./data/coffee.csv")
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [149]:
results=pd.read_parquet("./data/results.parquet")
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [150]:
# olympics_data=pd.read_excel("./data/olympics-data.xlsx",sheet_name="results")
# olympics_data.head()

In [151]:
bios=pd.read_csv("./data/bios.csv")
bios
# csv to excel file conversion
# bios.to_excel("./data/bios.xlsx", index=False, engine="openpyxl")

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

### Accessing Data with Pandas

In [152]:
coffee.head()
coffee.tail(7)
# print(coffee)
# display(coffee)
coffee.sample(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
1      Monday       Latte          15
13     Sunday       Latte          35
10   Saturday    Espresso          45
12     Sunday    Espresso          45
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25

In [153]:
coffee.loc[0] # based on index
coffee.loc[[1,2,3]]
coffee.loc[4:7]
print(coffee.loc[5:8,['Day','Units Sold']])
print(coffee.iloc[5:8,[0,2]])
# iloc the upper index is not inclusive and where with .loc it is inclusive
# coffee.index=coffee["Day"]
print(coffee.iloc[0:4,[0,2]])

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45
         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30
3  Tuesday          20

In [154]:
# edit
coffee.loc[1,"Units Sold"]=10

In [155]:
# Single Value
coffee.at[3,"Units Sold"]
coffee.iat[4,1]

'Espresso'

In [156]:
coffee["Day"] 
# or
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

### Sorting

In [157]:
coffee.sort_values(["Units Sold"],ascending=False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [158]:
coffee.sort_values(["Units Sold","Coffee Type"],ascending=[1,0])

          Day Coffee Type  Units Sold
1      Monday       Latte          10
3     Tuesday       Latte          20
5   Wednesday       Latte          25
0      Monday    Espresso          25
7    Thursday       Latte          30
2     Tuesday    Espresso          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [159]:
for index,row in  coffee.iterrows():
    print(index)
    print(row["Coffee Type"])
    print("\n\n\n\n\n")

0
Espresso






1
Latte






2
Espresso






3
Latte






4
Espresso






5
Latte






6
Espresso






7
Latte






8
Espresso






9
Latte






10
Espresso






11
Latte






12
Espresso






13
Latte

### Filtering Data

In [160]:
bios.loc[bios['height_cm']>215,['name',"height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [161]:
bios[bios['height_cm']>215][['name','height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [162]:
bios[(bios['height_cm']>215)&(bios['born_country']=='USA')][['name','born_country','height_cm']]

                    name born_country  height_cm
5781      Tommy Burleson          USA      223.0
6722    Shaquille O'Neal          USA      216.0
6937      David Robinson          USA      216.0
123850    Tyson Chandler          USA      216.0

In [163]:
bios[bios['name'].str.contains('Keith|Patrik',case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
136354,139579,Patrik Dalen,2004-03-11,Lørenskog,Viken,NOR,Norway,181.0,74.0,NaN
138662,142075,Patrik Šorm,1993-11-21,Praha (Prague),Hlavní město Praha,CZE,Czechia,NaN,NaN,NaN
138673,142087,Patrik Auda,1989-08-29,Ivančice,Jihomoravský kraj,CZE,Czechia,206.0,NaN,NaN
143068,146700,Patrik Jány,1997-07-29,Banská Štiavnica,Banská Bystrica,SVK,Slovakia,175.0,82.0,NaN
144918,148626,Patriks Ozols,2001-02-02,Rīga,Rīga,LAT,Latvia,NaN,NaN,NaN

In [164]:
bios[bios['born_country'].isin(['USA','FRA','GBR'])& (bios['name'].str.startswith('Keith'))][["name","born_country"]]

                      name born_country
3505         Keith Wallace          GBR
12053         Keith Hervey          GBR
14577       Keith Harrison          GBR
16166       Keith Reynolds          GBR
18734       Keith Sinclair          GBR
29897        Keith Langley          GBR
34011         Keith Remfry          GBR
46885         Keith Collin          GBR
50929         Keith Carter          USA
51185        Keith Russell          USA
52913       Keith Erickson          USA
55317         Keith Boxell          GBR
57818         Keith Peache          GBR
61748        Keith Grogono          GBR
62620          Keith Musto          GBR
62678         Keith Notary          USA
68324          Keith Angus          GBR
68472         Keith Cullen          GBR
68997          Keith Stock          GBR
77550        Keith Brantly          USA
84097   Keith Christiansen          USA
94646          Keith Meyer          USA
95267         Keith Oliver          GBR
96452   Keith Schellenberg          GBR
97499        Keith Tkachuk          USA
98068        Keith Wegeman          USA
99921         Keith Carney          USA
115973     Keith Sanderson          USA

In [165]:
bios.query('born_country=="USA" and born_city=="Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

### Adding/Removing Columns

In [166]:
# adding column
coffee['price']=4.99
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          10   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [167]:
import numpy as np

coffee['new_price']=np.where(coffee['Coffee Type']=='Espresso',3.99,5.99)
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          10   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [168]:
## remove row 
# coffee.drop(0)
# coffee=coffee.drop(0)
# coffee.drop(1)
# coffee.drop(1,inplace=True)
coffee = coffee[coffee["Units Sold"] >= 10]
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          10   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [169]:
# remove column
# both serve same purpose
coffee.drop(columns=['price'],inplace=True)
# coffee=coffee.drop(columns=['price'])
# coffee=coffee.drop(['Day','Coffee Type','Units Sold'])
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          10       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

### Copy

In [170]:
# it will stored the refrence any changes made to 'coffee_new' will reflect to 'coffee'
coffee_new=coffee
coffee_new['price']=4.99
# coffee_new
coffee

          Day Coffee Type  Units Sold  new_price  price
0      Monday    Espresso          25       3.99   4.99
1      Monday       Latte          10       5.99   4.99
2     Tuesday    Espresso          30       3.99   4.99
3     Tuesday       Latte          20       5.99   4.99
4   Wednesday    Espresso          35       3.99   4.99
5   Wednesday       Latte          25       5.99   4.99
6    Thursday    Espresso          40       3.99   4.99
7    Thursday       Latte          30       5.99   4.99
8      Friday    Espresso          45       3.99   4.99
9      Friday       Latte          35       5.99   4.99
10   Saturday    Espresso          45       3.99   4.99
11   Saturday       Latte          35       5.99   4.99
12     Sunday    Espresso          45       3.99   4.99
13     Sunday       Latte          35       5.99   4.99

In [171]:
# in this case it has store the copy anf both are pointing to different referecne
coffee_copy=coffee.copy()
coffee_copy["price"]=4.99
coffee_copy

          Day Coffee Type  Units Sold  new_price  price
0      Monday    Espresso          25       3.99   4.99
1      Monday       Latte          10       5.99   4.99
2     Tuesday    Espresso          30       3.99   4.99
3     Tuesday       Latte          20       5.99   4.99
4   Wednesday    Espresso          35       3.99   4.99
5   Wednesday       Latte          25       5.99   4.99
6    Thursday    Espresso          40       3.99   4.99
7    Thursday       Latte          30       5.99   4.99
8      Friday    Espresso          45       3.99   4.99
9      Friday       Latte          35       5.99   4.99
10   Saturday    Espresso          45       3.99   4.99
11   Saturday       Latte          35       5.99   4.99
12     Sunday    Espresso          45       3.99   4.99
13     Sunday       Latte          35       5.99   4.99

In [172]:
coffee['revenue']=coffee['Units Sold']*coffee['price']
coffee

          Day Coffee Type  Units Sold  new_price  price  revenue
0      Monday    Espresso          25       3.99   4.99   124.75
1      Monday       Latte          10       5.99   4.99    49.90
2     Tuesday    Espresso          30       3.99   4.99   149.70
3     Tuesday       Latte          20       5.99   4.99    99.80
4   Wednesday    Espresso          35       3.99   4.99   174.65
5   Wednesday       Latte          25       5.99   4.99   124.75
6    Thursday    Espresso          40       3.99   4.99   199.60
7    Thursday       Latte          30       5.99   4.99   149.70
8      Friday    Espresso          45       3.99   4.99   224.55
9      Friday       Latte          35       5.99   4.99   174.65
10   Saturday    Espresso          45       3.99   4.99   224.55
11   Saturday       Latte          35       5.99   4.99   174.65
12     Sunday    Espresso          45       3.99   4.99   224.55
13     Sunday       Latte          35       5.99   4.99   174.65

In [173]:
# rename
coffee.rename(columns={'new_price':'price'},inplace=True)
coffee=coffee.rename(columns={'new_price':'price'})

In [174]:
bios_new=bios.copy()

In [175]:
bios_new['first_name']=bios_new['name'].str.split(' ').str[0]

In [176]:
bios_new['born_date']=pd.to_datetime(bios_new['born_date'])

In [177]:
bios_new['born_year']=bios_new['born_date'].dt.year

In [178]:
# SAVE
bios_new.to_csv('./data/bios_new.csv',index=False);

In [179]:
#apply
bios['height_category']=bios['height_cm'].apply(lambda x : 'Short' if x<165 else('Average' if x<185 else 'Tall'))
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall

In [180]:
# apply using normal function
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
        return 'Middleweight'
    else:
        return 'Heavyweight'


bios['Category'] = bios.apply(categorize_athlete, axis=1)

In [181]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight

### Merging and Concatenating Data

In [182]:
nocs=pd.read_csv("./data/noc_regions.csv")
nocs.head()
# bios.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [183]:
bios_merge=pd.merge(bios,nocs,left_on='born_country',right_on='NOC', how='left',suffixes=['XX','yy'])

In [184]:
usa=bios[bios['born_country']=='USA'].copy()
gbr=bios[bios['born_country']=='GBR'].copy()
print(usa)

        athlete_id               name   born_date         born_city  \
54              55      Monique Javer  1967-07-22        Burlingame
960            964   Xóchitl Escobedo  1968-09-17       West Covina
961            965  Angélica Gavaldón  1973-10-03         El Centro
1231          1238     Bert Schneider  1897-07-01         Cleveland
1345          1352         Laura Berg  1975-01-06  Santa Fe Springs
...            ...                ...         ...               ...
145445      149168     Kristen Santos  1994-11-02         Fairfield
145446      149169   Corinne Stoddard  2001-08-15           Seattle
145454      149180      Anna Hoffmann  2000-03-28           Madison
145457      149183     Alix Wilkinson  2000-08-02     Mammoth Lakes
145468      149195  Justin Abdelkader  1987-02-25          Muskegon

        born_region born_country            NOC  height_cm  weight_kg  \
54       California          USA  Great Britain      177.0       64.0
960      California          USA         Mexico      170.0       60.0
961      California          USA         Mexico      160.0       54.0
1231           Ohio          USA         Canada        NaN        NaN
1345     California          USA  United States      168.0       61.0
...             ...          ...            ...        ...        ...
145445  Connecticut          USA  United States        NaN        NaN
145446   Washington          USA  United States        NaN        NaN
145454    Wisconsin          USA  United States        NaN        NaN
145457   California          USA  United States        NaN        NaN
145468     Michigan          USA  United States      187.0       97.0

         died_date height_category      Category
54             NaN         Average  Middleweight
960            NaN         Average   Lightweight
961            NaN           Short   Lightweight
1231    1986-02-20            Tall   Heavyweight
1345           NaN         Average   Lightweight
...            ...             ...           ...
145445         NaN            Tall   Heavyweight
145446         NaN            Tall   Heavyweight
145454         NaN            Tall   Heavyweight
145457         NaN            Tall   Heavyweight
145468         NaN            Tall   Heavyweight

[9641 rows x 12 columns]

In [185]:
#concat
new_df=pd.concat([usa,gbr])
new_df.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,Tall,Heavyweight
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,Tall,Heavyweight
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,Average,Middleweight
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,Tall,Heavyweight
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,Tall,Heavyweight

In [186]:
results

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [187]:
combined_df=pd.merge(results,bios,on='athlete_id',how='left')
combined_df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,...,2001-07-12,Gelnica,Košice,SVK,Slovakia,196.0,108.0,NaN,Tall,Heavyweight
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,...,1998-03-28,Vemdalen,Jämtland,SWE,Sweden,NaN,NaN,NaN,Tall,Heavyweight
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,...,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN,Tall,Heavyweight
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,...,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN,Tall,Heavyweight
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,...,1994-10-07,Kungsbacka,Halland,SWE,Sweden,NaN,NaN,NaN,Tall,Heavyweight

### Handling Null Values

In [188]:
coffee.loc[[2,3],['Units Sold']]=np.nan
coffee

          Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso        25.0   3.99   4.99   124.75
1      Monday       Latte        10.0   5.99   4.99    49.90
2     Tuesday    Espresso         NaN   3.99   4.99   149.70
3     Tuesday       Latte         NaN   5.99   4.99    99.80
4   Wednesday    Espresso        35.0   3.99   4.99   174.65
5   Wednesday       Latte        25.0   5.99   4.99   124.75
6    Thursday    Espresso        40.0   3.99   4.99   199.60
7    Thursday       Latte        30.0   5.99   4.99   149.70
8      Friday    Espresso        45.0   3.99   4.99   224.55
9      Friday       Latte        35.0   5.99   4.99   174.65
10   Saturday    Espresso        45.0   3.99   4.99   224.55
11   Saturday       Latte        35.0   5.99   4.99   174.65
12     Sunday    Espresso        45.0   3.99   4.99   224.55
13     Sunday       Latte        35.0   5.99   4.99   174.65

In [189]:
# to check NA count
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
price          0
price          0
revenue        0
dtype: int64

In [190]:
# fill "NA" value
coffee=coffee.fillna(coffee['Units Sold'].mean())
coffee

          Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso       25.00   3.99   4.99   124.75
1      Monday       Latte       10.00   5.99   4.99    49.90
2     Tuesday    Espresso       33.75   3.99   4.99   149.70
3     Tuesday       Latte       33.75   5.99   4.99    99.80
4   Wednesday    Espresso       35.00   3.99   4.99   174.65
5   Wednesday       Latte       25.00   5.99   4.99   124.75
6    Thursday    Espresso       40.00   3.99   4.99   199.60
7    Thursday       Latte       30.00   5.99   4.99   149.70
8      Friday    Espresso       45.00   3.99   4.99   224.55
9      Friday       Latte       35.00   5.99   4.99   174.65
10   Saturday    Espresso       45.00   3.99   4.99   224.55
11   Saturday       Latte       35.00   5.99   4.99   174.65
12     Sunday    Espresso       45.00   3.99   4.99   224.55
13     Sunday       Latte       35.00   5.99   4.99   174.65

In [191]:
coffee.loc[[0,1],['Units Sold']]=15
coffee

          Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso       15.00   3.99   4.99   124.75
1      Monday       Latte       15.00   5.99   4.99    49.90
2     Tuesday    Espresso       33.75   3.99   4.99   149.70
3     Tuesday       Latte       33.75   5.99   4.99    99.80
4   Wednesday    Espresso       35.00   3.99   4.99   174.65
5   Wednesday       Latte       25.00   5.99   4.99   124.75
6    Thursday    Espresso       40.00   3.99   4.99   199.60
7    Thursday       Latte       30.00   5.99   4.99   149.70
8      Friday    Espresso       45.00   3.99   4.99   224.55
9      Friday       Latte       35.00   5.99   4.99   174.65
10   Saturday    Espresso       45.00   3.99   4.99   224.55
11   Saturday       Latte       35.00   5.99   4.99   174.65
12     Sunday    Espresso       45.00   3.99   4.99   224.55
13     Sunday       Latte       35.00   5.99   4.99   174.65

In [192]:
# interpolate() is a Pandas method used to fill missing (NaN) values by estimating values based on the surrounding known values.
coffee["Units Sold"]=coffee["Units Sold"].interpolate()
coffee

          Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso       15.00   3.99   4.99   124.75
1      Monday       Latte       15.00   5.99   4.99    49.90
2     Tuesday    Espresso       33.75   3.99   4.99   149.70
3     Tuesday       Latte       33.75   5.99   4.99    99.80
4   Wednesday    Espresso       35.00   3.99   4.99   174.65
5   Wednesday       Latte       25.00   5.99   4.99   124.75
6    Thursday    Espresso       40.00   3.99   4.99   199.60
7    Thursday       Latte       30.00   5.99   4.99   149.70
8      Friday    Espresso       45.00   3.99   4.99   224.55
9      Friday       Latte       35.00   5.99   4.99   174.65
10   Saturday    Espresso       45.00   3.99   4.99   224.55
11   Saturday       Latte       35.00   5.99   4.99   174.65
12     Sunday    Espresso       45.00   3.99   4.99   224.55
13     Sunday       Latte       35.00   5.99   4.99   174.65

In [193]:
# drop 
# coffee.dropna()
# or 
coffee=coffee.dropna(subset=["Units Sold"])

In [194]:
coffee[coffee['Units Sold'].isna()]
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso       15.00   3.99   4.99   124.75
1      Monday       Latte       15.00   5.99   4.99    49.90
2     Tuesday    Espresso       33.75   3.99   4.99   149.70
3     Tuesday       Latte       33.75   5.99   4.99    99.80
4   Wednesday    Espresso       35.00   3.99   4.99   174.65
5   Wednesday       Latte       25.00   5.99   4.99   124.75
6    Thursday    Espresso       40.00   3.99   4.99   199.60
7    Thursday       Latte       30.00   5.99   4.99   149.70
8      Friday    Espresso       45.00   3.99   4.99   224.55
9      Friday       Latte       35.00   5.99   4.99   174.65
10   Saturday    Espresso       45.00   3.99   4.99   224.55
11   Saturday       Latte       35.00   5.99   4.99   174.65
12     Sunday    Espresso       45.00   3.99   4.99   224.55
13     Sunday       Latte       35.00   5.99   4.99   174.65

### Data Aggregation

In [195]:
bios[bios['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Tennessee                 62
Kentucky                  62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [196]:
#sum
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    258.75
Latte       208.75
Name: Units Sold, dtype: float64

In [197]:
#avg
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    36.964286
Latte       29.821429
Name: Units Sold, dtype: float64

In [198]:
coffee.groupby(['Coffee Type']).agg({'Units Sold':'mean','price':'sum'})

             Units Sold  price  price
Coffee Type
Espresso      36.964286  27.93  34.93
Latte         29.821429  41.93  34.93

In [199]:
# mutiple group by
coffee.groupby(['Coffee Type','Day']).agg({'Units Sold':'mean','price':'sum'})

                       Units Sold  price  price
Coffee Type Day
Espresso    Friday          45.00   3.99   4.99
            Monday          15.00   3.99   4.99
            Saturday        45.00   3.99   4.99
            Sunday          45.00   3.99   4.99
            Thursday        40.00   3.99   4.99
            Tuesday         33.75   3.99   4.99
            Wednesday       35.00   3.99   4.99
Latte       Friday          35.00   5.99   4.99
            Monday          15.00   5.99   4.99
            Saturday        35.00   5.99   4.99
            Sunday          35.00   5.99   4.99
            Thursday        30.00   5.99   4.99
            Tuesday         33.75   5.99   4.99
            Wednesday       25.00   5.99   4.99

### Pivot and Pivot Tables

In [200]:
pivot=coffee.pivot(columns='Coffee Type', index='Day',values='revenue')
print(pivot)

Coffee Type  Espresso   Latte
Day
Friday         224.55  174.65
Monday         124.75   49.90
Saturday       224.55  174.65
Sunday         224.55  174.65
Thursday       199.60  149.70
Tuesday        149.70   99.80
Wednesday      174.65  124.75

In [204]:
bios['born_date']=pd.to_datetime(bios['born_date'])
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index().sort_values('name',ascending=False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
4       1837.0     1
2       1833.0     1
6       1839.0     1
12      1845.0     1
176     2009.0     1

[177 rows x 2 columns]

In [ ]:
bios['month_born']=bios['born_date'].dt.month
bios['year_born']=bios['born_date'].dt.year
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name',ascending=False)

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

## Advanced Functionality 
### .shift() .rank() .rolling() .cumsum()

In [ ]:
# shift(1)-> previous row value
# shift(-1)-> next row value
coffee['yesterday_revenue']=coffee['revenue'].shift(2)

In [ ]:
# rank()
bios['height_rank']=bios['height_cm'].rank(ascending=True)

In [ ]:
bios.sort_values(['height_rank']).sample(10)[['name','height_rank']]

# head()-> first n rows 
# sample()->  show n random rows

                    name  height_rank
447    Marie-Josée Bazin      40572.0
21930     David Bartlett          NaN
37958    Paola Grizzetti      63580.5
37144       John Ranking          NaN
76321         Euric Bobb      79054.5
29996       Jürgen Paeke      25624.5
38811     Sigurd Monssen          NaN
66121      David Njitock      48271.5
17841         Denis Daly          NaN
20389     Emilie Schwind          NaN

In [ ]:
# cumsum
coffee['cumulative_revenue']=coffee['revenue'].cumsum()

In [ ]:
#rolling 

latte=coffee[coffee['Coffee Type']=='Latte'].copy()
latte['3day']=latte['Units Sold'].rolling(3).sum()
print(latte)

          Day Coffee Type  Units Sold   revenue  price  yesterday_revenue  \
1      Monday       Latte       15.00   89.8500   5.99                NaN
3     Tuesday       Latte       33.75  202.1625   5.99            89.8500
5   Wednesday       Latte       25.00  149.7500   5.99           202.1625
7    Thursday       Latte       30.00  179.7000   5.99           149.7500
9      Friday       Latte       35.00  209.6500   5.99           179.7000
11   Saturday       Latte       35.00  209.6500   5.99           209.6500
13     Sunday       Latte       35.00  209.6500   5.99           209.6500

    cumulative_revenue    3day
1              149.700     NaN
3              486.525     NaN
5              775.925   73.75
7             1115.225   88.75
9             1504.425   90.00
11            1893.625  100.00
13            2282.825  105.00

In [ ]:
import pandas as pd

# Creating a DataFrame
data = {
    'Date': ['2024-05-01', '2024-05-01', '2024-05-01', '2024-05-02', '2024-05-02', '2024-05-03', '2024-05-03', '2024-05-03'],
    'Item': ['Apple', 'Banana', 'Orange', 'Apple', 'Banana', 'Orange', 'Apple', 'Orange'],
    'Units Sold': [30, 21, 15, 40, 34, 20, 45, 25],
    'Price Per Unit': [1.0, 0.5, 0.75, 1.0, 0.5, 0.75, 1.0, 0.75],
    'Salesperson': ['John', 'John', 'John', 'Alice', 'Alice', 'John', 'Alice', 'John']
}

df = pd.DataFrame(data)

# Display the DataFrame
df

         Date    Item  Units Sold  Price Per Unit Salesperson
0  2024-05-01   Apple          30            1.00        John
1  2024-05-01  Banana          21            0.50        John
2  2024-05-01  Orange          15            0.75        John
3  2024-05-02   Apple          40            1.00       Alice
4  2024-05-02  Banana          34            0.50       Alice
5  2024-05-03  Orange          20            0.75        John
6  2024-05-03   Apple          45            1.00       Alice
7  2024-05-03  Orange          25            0.75        John

In [ ]:

pivot_table = pd.pivot_table(df, values='Units Sold', index='Date', columns='Item', aggfunc='sum')
pivot_table

Item        Apple  Banana  Orange
Date
2024-05-01   30.0    21.0    15.0
2024-05-02   40.0    34.0     NaN
2024-05-03   45.0     NaN    45.0

In [ ]:
# pivot()
# - Reshapes data from long format to wide format.
# - Does NOT perform aggregation.
# - Each index + column combination must be unique.
# - Duplicate combinations → ValueError.

df.pivot(
    index='Day',
    columns='Coffee Type',
    values='Units Sold'
)


# pivot_table()
# - Reshapes data AND performs aggregation.
# - Handles duplicate index + column combinations.
# - Uses aggfunc to decide how to combine values.
# - Default aggfunc = 'mean'.

df.pivot_table(
    index='Day',
    columns='Coffee Type',
    values='Units Sold',
    aggfunc='sum'
)

# Common aggfunc:
# 'sum', 'mean', 'count', 'min', 'max'

In [206]:
coffee

          Day Coffee Type  Units Sold  price  price  revenue
0      Monday    Espresso       15.00   3.99   4.99   124.75
1      Monday       Latte       15.00   5.99   4.99    49.90
2     Tuesday    Espresso       33.75   3.99   4.99   149.70
3     Tuesday       Latte       33.75   5.99   4.99    99.80
4   Wednesday    Espresso       35.00   3.99   4.99   174.65
5   Wednesday       Latte       25.00   5.99   4.99   124.75
6    Thursday    Espresso       40.00   3.99   4.99   199.60
7    Thursday       Latte       30.00   5.99   4.99   149.70
8      Friday    Espresso       45.00   3.99   4.99   224.55
9      Friday       Latte       35.00   5.99   4.99   174.65
10   Saturday    Espresso       45.00   3.99   4.99   224.55
11   Saturday       Latte       35.00   5.99   4.99   174.65
12     Sunday    Espresso       45.00   3.99   4.99   224.55
13     Sunday       Latte       35.00   5.99   4.99   174.65